# Grundinfo
title: "vår."
description: "Ett utrymme för vår diskussion"


# Viktigt för länkar
url: "https://crocus-vernus.github.io/var/"
baseurl: "/var" # tomt ("") om repo heter Crocus-vernus.github.io


# Tema & plugins som stöds av GitHub Pages
theme: minima
plugins:
- jekyll-feed
- jekyll-seo-tag


# Styr om sajten ska vara dold bakom "Kommer snart"
coming_soon: false # ändra till false när du lanserar


# Språk (påverkar bl.a. datumformat i vissa teman)
lang: sv-SE


# Bloggstruktur
collections:
posts:
output: true

